from pathlib import Path
import argparse
import os
import sys
from typing import Optional


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_SOURCE = (SCRIPT_DIR.parent / "keys" / "permanent_public.pem").resolve()
TARGET_FILE = SCRIPT_DIR / "lib" / "data" / "generated_public_key.dart"

PLACEHOLDER_CONTENT = """const String generatedPublicKeyPem = '';
"""


def render_public_key_dart(pem_text: str) -> str:
    normalized = pem_text.replace("\r\n", "\n").strip()
    return (
        "// This file is generated by generate_public_key_dart.py.\n"
        "// Do not commit real key material to a public repository.\n"
        "const String generatedPublicKeyPem = r'''\n"
        f"{normalized}\n"
        "''';\n"
    )


def resolve_source_path(explicit_source: Optional[str]) -> Path:
    if explicit_source:
        return Path(explicit_source).expanduser().resolve()
    env_source = os.getenv("IMAGE_PROVIDER_PUBLIC_KEY_PATH", "").strip()
    if env_source:
        return Path(env_source).expanduser().resolve()
    return DEFAULT_SOURCE


def write_placeholder() -> None:
    TARGET_FILE.parent.mkdir(parents=True, exist_ok=True)
    TARGET_FILE.write_text(PLACEHOLDER_CONTENT, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate flutter_client_app/lib/data/generated_public_key.dart from a PEM public key.",
    )
    parser.add_argument(
        "--source",
        help="Path to the PEM public key file. Defaults to IMAGE_PROVIDER_PUBLIC_KEY_PATH or ../keys/permanent_public.pem.",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Restore generated_public_key.dart to the empty placeholder state.",
    )
    args = parser.parse_args()

    if args.clear:
        write_placeholder()
        print(f"Cleared generated key file: {TARGET_FILE}")
        return 0

    source_path = resolve_source_path(args.source)
    if not source_path.exists():
        print(f"Public key file not found: {source_path}", file=sys.stderr)
        return 1

    pem_text = source_path.read_text(encoding="utf-8-sig")
    normalized = pem_text.strip()
    if "BEGIN PUBLIC KEY" not in normalized or "END PUBLIC KEY" not in normalized:
        print(f"Invalid PEM public key file: {source_path}", file=sys.stderr)
        return 1

    TARGET_FILE.parent.mkdir(parents=True, exist_ok=True)
    TARGET_FILE.write_text(
        render_public_key_dart(normalized),
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated Flutter public key file: {TARGET_FILE}")
    print(f"Source PEM: {source_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())