// This file is generated by generate_public_key_dart.py.
// Do not commit real key material to a public repository.
const String generatedPublicKeyPem = r'''
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6v+UCjDeSOO0LCPY+Kr/
zh+gvMAbiBKaboh1sd3BSn70sQP+b5ZkM/tjQIe9KKpA+uc94yCZZYhpeMbBpKOj
V0DwXJpqGCphC6dINIZTYYD+M+2+zqdcLj7yh2GdjvqHYKP3/TUbFgVvLLri9l6R
DTPrDnb7ovLonlBnIY3P4+UIYs6MeO02QXa04ZdlWsXctQZUwjsbasMEty+o+EOO
wrWAS23h6/8PoHkrHWGCbLPa8XSUTZLiWgYZZh8jmB3HAJWbLE+fUEcGwJjMbfmC
Nl4WHdUJ8BwvD30wGwZKbH0axbtcG2HhP/nQb9MJro4R15SAJ+3UoMJIL2kVxRgU
cwIDAQAB
-----END PUBLIC KEY-----
''';
